/*
 * Timer23.c
 *
 *  Created on: 1 Jul 2020
 *      Author: Nicolas
 */

#include <EFM8SBx_Timer23.h>

SI_SEGMENT_VARIABLE(timer_ticks, uint16_t, SI_SEG_XDATA) = 0;

void Timer2_Initialize()
{
	// By default to count each 1 ms
	TMR2CN0 = 0x00;
	TMR2H = 0xFF;
	TMR2L = 0x01;
	TMR2RLH = 0xF8;
	TMR2RLL = 0x06;
}

void delay_ms(uint16_t milliseconds)
{
	// start timer 2
	TMR2CN0_TR2 = 1;
	// clean timer 2 counter registers
	TMR2H = 0x00;
	TMR2L = 0x00;

	// busy wait
	while (timer_ticks < milliseconds)
		;
	// stop timer 2
	TMR2CN0_TR2 = 0;
	// reset milliseconds count generated by ISR
	timer_ticks = 0;
}

//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
//
// TIMER2 ISR Content goes here. Remember to clear flag bits:
// TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
// TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
{
	// one timer tick / millisecond
	timer_ticks++;
	// Clean Timer 2 overflow flags
	TMR2CN0_TF2H = 0;
	TMR2CN0_TF2L = 0;
}
